-- MySQL Script generated by MySQL Workbench
-- 06/06/16 14:43:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lab2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab2` DEFAULT CHARACTER SET utf8 ;
USE `lab2` ;

-- -----------------------------------------------------
-- Table `lab2`.`Journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`Journal` (
  `idJournal` INT NOT NULL AUTO_INCREMENT,
  `titleJournal` VARCHAR(45) NULL,
  `publisher` VARCHAR(45) NULL,
  PRIMARY KEY (`idJournal`),
  FULLTEXT INDEX `full_text` (`publisher` ASC),
  UNIQUE INDEX `idJournal_UNIQUE` (`idJournal` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`Book` (
  `idBook` INT NOT NULL AUTO_INCREMENT,
  `titleBook` VARCHAR(45) NULL,
  `author` VARCHAR(45) NULL,
  `publisherBook` VARCHAR(45) NULL,
  PRIMARY KEY (`idBook`),
  FULLTEXT INDEX `full_text` (`publisherBook` ASC),
  UNIQUE INDEX `idBook_UNIQUE` (`idBook` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`Buyer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`Buyer` (
  `idBuyer` INT NOT NULL AUTO_INCREMENT,
  `nameBuyer` VARCHAR(45) NULL,
  `surnameBuyer` VARCHAR(45) NULL,
  `age` VARCHAR(45) NULL,
  PRIMARY KEY (`idBuyer`),
  UNIQUE INDEX `idBuyer_UNIQUE` (`idBuyer` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab2`.`Purchase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab2`.`Purchase` (
  `idPurchase` INT NOT NULL AUTO_INCREMENT,
  `buyDate` DATE NULL,
  `price` INT NULL,
  `journal` INT NOT NULL,
  `book` INT NOT NULL,
  `buyer` INT NOT NULL,
  PRIMARY KEY (`idPurchase`, `journal`, `book`, `buyer`),
  INDEX `fk_Purchase_Journal_idx` (`journal` ASC),
  INDEX `fk_Purchase_Book1_idx` (`book` ASC),
  INDEX `fk_Purchase_Buyer1_idx` (`buyer` ASC),
  UNIQUE INDEX `idPurchase_UNIQUE` (`idPurchase` ASC),
  CONSTRAINT `fk_Purchase_Journal`
    FOREIGN KEY (`journal`)
    REFERENCES `lab2`.`Journal` (`idJournal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Book1`
    FOREIGN KEY (`book`)
    REFERENCES `lab2`.`Book` (`idBook`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchase_Buyer1`
    FOREIGN KEY (`buyer`)
    REFERENCES `lab2`.`Buyer` (`idBuyer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
